[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sales-forecasting"
version = "0.1.0"
description = "Sales orders from supply chain graph"

[tool.setuptools.packages.find]
where = ["."]
include = ["sales_forecasting*"]